name = "davora"
main = "src/index.ts"
compatibility_date = "2026-05-03"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

  [observability.logs]
  enabled = true
  head_sampling_rate = 1

  [observability.traces]
  enabled = true
  head_sampling_rate = 1

[[durable_objects.bindings]]
name = "DAVORA_ACCOUNT_STORE"
class_name = "AccountStoreDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AccountStoreDurableObject"]
